@startuml 05_Transport_Fahrt_NextNode_Rerouting
skinparam backgroundColor #FFFFFF

skinparam sequence {
ArrowColor #8A0808
LifeLineBorderColor #8A0808

ParticipantBorderColor #8A0808
ParticipantBackgroundColor #585858
ParticipantFontColor #FFFFFF
}

skinparam note {
borderColor #000000
backgroundColor #E6E6E6
}

participant "**Transport Service**\n**(ID: transA)**" as TOA order 2
participant "**Transport Management**\n**with**\n**AGV System Adapter**" as Adapter order 3
participant "**AGV**\n**System**" as FMS order 4

activate Adapter
activate TOA
activate FMS

note over TOA
EXECUTE,
TransferFromLeaSucceeded
end note

TOA -->> Adapter: ProcedureCur: 16#9\n(TransferFromLea-\nSucceeded)

Adapter ->> FMS: Drive to transport node\nwith ID: 3
FMS ->> Adapter: Transport is being executed

Adapter ->> TOA: ProcuedureExt := 16#3\n(Transport)
Adapter ->> TOA: CommandExt := 512\n(Restart)

note over TOA
EXECUTE,
Transport
end note

group Optional rerouting

note over Adapter: Connection to the target LEA lost or\nTransportClientManager.LeaStateCur\nindicates error state

note over Adapter: LOL-internal determination of an\nalternative transport node X to approach

Adapter ->> TOA: NextNode := X
Adapter ->> TOA: ProcedureExt := 16#F\n(Rerouting)
Adapter ->> TOA: CommandExt := 512\n(Restart)

note over TOA
EXECUTE,
Rerouting
end note

TOA -->> Adapter: ProcedureCur: 16#E\n(Rerouting)

Adapter ->> FMS: Drive to transport node\nwith ID: X
FMS ->> Adapter: Transport is being executed

Adapter ->> TOA: ProcedureExt := 16#3\n(Transport)
Adapter ->> TOA: CommandExt := 512\n(Restart)

note over TOA
EXECUTE,
Transport
end note



end group


@enduml
