@startuml 04_TransportNodeRequest
skinparam backgroundColor #FFFFFF

skinparam sequence {
ArrowColor #8A0808
LifeLineBorderColor #8A0808

ParticipantBorderColor #8A0808
ParticipantBackgroundColor #585858
ParticipantFontColor #FFFFFF
}

skinparam note {
borderColor #000000
backgroundColor #E6E6E6
}

participant "**LOL**" as DZ order 1
participant "**LEA Service**" as Service order 2

note over Service
LogisticsInteraction
--
LogisticsQuestionID[-1]: No question
LogisticsQuestionID[5]: TransportNodeRequest
..
LogisticsAnswerID[-2]: Error
LogisticsAnswerID[-1]: No answer
LogisticsAnswerID[0]: Use of FinalTargetNode
LogisticsAnswerID[>0]: ID of the next transport node
..
LogisticsQuestionParam1: ' '
LogisticsQuestionParam2: ' '
end note

DZ <<- Service: LogisticsQuestionID: 5\nLogisticsQuestionParam1: 'Transport0815' (TransportId)\nLogisticsQuestionParam2: ' ' (not used)

hnote over DZ
Determination of the next
transport node for Transport 0815
end hnote

group IF next transport node specified directly as answer

DZ ->> Service: LogisticsAnswerID := 4

hnote over Service
Next transport node to be approached
is the node with ID = 4
end hnote

end group

group IF next transport node specified via FinalTargetNode

DZ ->> Service: LogisticsAnswerID := 0

hnote over Service
Next transport node to be approached
shall be obtained from FinalTargetNode
end hnote

end group


DZ <<- Service: LogisticsQuestionID := -1\nLogisticsQuestionParam1 := ' '\nLogisticsQuestionParam2 := ' '
DZ ->> Service: LogisticsAnswerID := -1

@enduml
