@startuml 04_ProductParameterRequest
skinparam backgroundColor #FFFFFF

skinparam sequence {
ArrowColor #8A0808
LifeLineBorderColor #8A0808

ParticipantBorderColor #8A0808
ParticipantBackgroundColor #585858
ParticipantFontColor #FFFFFF
}

skinparam note {
borderColor #000000
backgroundColor #E6E6E6
}

participant "**LOL**" as DZ order 1
participant "**LEA Service**" as Service order 2

note over Service
LogisticsInteraction
--
LogisticsQuestionID[-1]: No question
LogisticsQuestionID[1]: ProductParameterRequest
..
LogisticsAnswerID[-2]: Error
LogisticsAnswerID[-1]: No answer
LogisticsAnswerID[>=0]: Index of the modified parameter set
in ProductDataSet
..
LogisticsQuestionParam1: ' '
LogisticsQuestionParam2: ' '
end note

DZ <<- Service: LogisticsQuestionID: 1\nLogisticsQuestionParam1: 'X' (ProductId)\nLogisticsQuestionParam2: 'Y' (LogisticsObjectStatus)

hnote over DZ
Determination of the parameter set
end hnote

DZ ->> Service: Parameterization via ArrayServParam\nof ProductDataSet
DZ ->> Service: LogisticsAnswerID := 3 (Index 3)

hnote over Service
New parameter set has been written to 
index 3 of the LEA-internal ProductDataSet
end hnote

DZ <<- Service: LogisticsQuestionID := -1\nLogisticsQuestionParam1 := ' '\nLogisticsQuestionParam2 := ' '
DZ ->> Service: LogisticsAnswerID := -1

@enduml
